name: Run lint and test for app directory

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/app-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: lint
        run: make lint
      - name: test
        run: make test
