name: Deploy app

on:
  push:
    tags:
      - "app/v1*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: "Deploy to Cloud Run"
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          image: "gcr.io/cloudrun/hello"
          service: "expapp"
          region: "asia-northeast1"
