name: Run lint and test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - name: lint
        run: make lint
      - name: test
        run: make test
